server:   
   port : 8084
appwale:   
   auth:   
      server:
         url:  http://localhost:8085/oauth/token 
      client_id:   acme
      client_secret:   acmesecret
      redirect_uri:   http://127.0.0.1:8084/authCode
      code:   
      grant_type:   authorization_code
      response_type : code 
      code_url: http://localhost:8085/oauth/authorize
      